# Generated by Django 5.0.6 on 2024-07-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_tourpackage_tourimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='t_image',
            field=models.ImageField(default='abc.jpg', upload_to='tour'),
        ),
    ]
