# Generated by Django 5.0.6 on 2024-07-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_faqs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faqs',
        ),
    ]
