# Generated by Django 5.0.6 on 2024-07-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_destination_india_part_destination_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='no_of_packages',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price_range',
        ),
    ]
