# Generated by Django 5.0.6 on 2024-07-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_destination_no_of_packages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='india_part',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
