# Generated by Django 5.0.6 on 2024-07-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_destination_india_part_alter_destination_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='tags',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('Most Viewed', 'Most Viewed'), ('Discounted', 'Discounted'), ('50% off', '50% off')], max_length=100, null=True),
        ),
    ]
