# Generated by Django 5.0.6 on 2024-07-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_destination_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='tags',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Most Viewed', 'Most Viewed'), ('Discounted', 'Discounted'), ('50% off', '50% off')], max_length=100, null=True),
        ),
    ]
