# Generated by Django 5.0.6 on 2024-07-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_destination_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='no_of_people',
            field=models.IntegerField(default=0),
        ),
    ]
