# Generated by Django 5.0.6 on 2024-07-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_tourpackage_no_of_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='map_iframe',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='t_image',
            field=models.ImageField(upload_to='tour'),
        ),
    ]
