# Generated by Django 5.0.6 on 2024-07-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_tourpackage_map_iframe_alter_tourpackage_t_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='location',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='included',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='not_included',
            field=models.TextField(default=''),
        ),
    ]
