# Generated by Django 5.0.6 on 2024-07-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_tourpackage_location_tourpackage_included_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
