# Generated by Django 5.0.6 on 2024-07-27 05:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_tourpackage_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('heading1', models.TextField()),
                ('desc1', models.TextField()),
                ('heading2', models.TextField()),
                ('desc2', models.TextField()),
                ('heading3', models.TextField()),
                ('desc3', models.TextField()),
                ('heading4', models.TextField()),
                ('desc4', models.TextField()),
                ('heading5', models.TextField()),
                ('desc5', models.TextField()),
                ('heading6', models.TextField()),
                ('desc6', models.TextField()),
                ('heading7', models.TextField()),
                ('desc7', models.TextField()),
                ('heading8', models.TextField()),
                ('desc8', models.TextField()),
                ('heading9', models.TextField()),
                ('desc9', models.TextField()),
                ('heading10', models.TextField()),
                ('desc10', models.TextField()),
                ('heading11', models.TextField()),
                ('desc11', models.TextField()),
                ('heading12', models.TextField()),
                ('desc12', models.TextField()),
                ('heading13', models.TextField()),
                ('desc13', models.TextField()),
                ('heading14', models.TextField()),
                ('desc14', models.TextField()),
                ('heading15', models.TextField()),
                ('desc15', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='home.tourpackage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
