# Generated by Django 5.0.6 on 2024-07-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='itinerary',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
    ]
