# Generated by Django 5.0.6 on 2024-07-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_tourpackage_itinerary_delete_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='tags',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Most Viewed', 'Most Viewed'), ('Discounted', 'Discounted'), ('50% Off', '50% Off')], max_length=100, null=True),
        ),
    ]
