# Generated by Django 5.0.6 on 2024-08-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_homeabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeabout',
            name='countries',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='years',
            field=models.IntegerField(default=20),
        ),
    ]
