# Generated by Django 5.0.6 on 2024-08-01 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_homeabout_countries_homeabout_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
