# Generated by Django 5.0.6 on 2024-08-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_achievements'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
