# Generated by Django 5.0.6 on 2024-08-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='no_of_children',
            field=models.IntegerField(default=0),
        ),
    ]
