# Generated by Django 5.0.6 on 2024-08-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_tourpackage_no_of_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('National', 'National'), ('International', 'International')], default='National', max_length=100),
        ),
    ]
