# Generated by Django 5.0.6 on 2024-08-09 11:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_destination_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplePackage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('t_image', models.ImageField(upload_to='temple')),
                ('date_of_travel', models.DateField()),
                ('no_of_people', models.IntegerField()),
                ('no_of_children', models.IntegerField()),
                ('map_iframe', models.CharField(max_length=255)),
                ('included', models.TextField()),
                ('not_included', models.TextField()),
                ('itinerary', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempleImage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='temple')),
                ('temple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temple_images', to='home.templepackage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
