# Generated by Django 5.0.6 on 2024-08-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_templepackage_templeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templepackage',
            name='map_iframe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
