# Generated by Django 5.0.6 on 2024-08-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_templepackage_map_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templepackage',
            name='t_image',
            field=models.ImageField(default='42.jpg', upload_to='temple'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='t_image',
            field=models.ImageField(default='38.jpg', upload_to='tour'),
        ),
    ]
