# Generated by Django 5.0.6 on 2024-08-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_templepackage_t_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templeimage',
            name='image',
            field=models.ImageField(default='42.jpg', upload_to='temple'),
        ),
    ]
