# Generated by Django 5.0.6 on 2024-08-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_templeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templeimage',
            name='image',
            field=models.ImageField(default='temple/42.jpg', upload_to='temple'),
        ),
    ]
