# Generated by Django 5.0.6 on 2024-08-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_templeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templepackage',
            name='t_image',
            field=models.ImageField(default='temple/42.jpg', upload_to='temple'),
        ),
    ]
