# Generated by Django 5.0.6 on 2024-08-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_templepackage_t_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templeimage',
            name='image',
            field=models.ImageField(upload_to='temple'),
        ),
        migrations.AlterField(
            model_name='templepackage',
            name='t_image',
            field=models.ImageField(upload_to='temple'),
        ),
    ]
