# Generated by Django 5.0.6 on 2024-08-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_templeimage_image_alter_templepackage_t_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templeimage',
            name='image',
            field=models.ImageField(default='size:775x609', upload_to='temple'),
        ),
        migrations.AlterField(
            model_name='templepackage',
            name='t_image',
            field=models.ImageField(blank=True, default='size:775x609', null=True, upload_to='temple'),
        ),
    ]
