# Generated by Django 5.0.6 on 2024-08-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_templeimage_image_alter_templepackage_t_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templeimage',
            name='image',
            field=models.ImageField(upload_to='temple'),
        ),
        migrations.AlterField(
            model_name='templepackage',
            name='t_image',
            field=models.ImageField(blank=True, null=True, upload_to='temple'),
        ),
    ]
