# Generated by Django 5.0.6 on 2024-08-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_templeimage_image_alter_templepackage_t_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('National', 'National'), ('International', 'International')], default='International', max_length=100),
        ),
    ]
