# Generated by Django 5.0.6 on 2024-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_destination_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='video_file',
            field=models.FileField(default='1.mp4', upload_to='videos/'),
        ),
    ]
