# Generated by Django 5.0.6 on 2024-08-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_destination_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('National', 'National'), ('International', 'International')], default='National', max_length=100),
        ),
    ]
