# Generated by Django 5.0.6 on 2024-08-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_alter_destination_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='video_file',
            field=models.CharField(max_length=255),
        ),
    ]
