# Generated by Django 5.0.6 on 2024-08-13 10:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_destination_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(max_length=100)),
                ('package_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_booking', to='home.tourpackage')),
            ],
        ),
    ]
