# Generated by Django 5.0.6 on 2024-08-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_livebooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveBooking',
        ),
    ]
