# Generated by Django 5.0.6 on 2024-08-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='termsnconditions',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
